import type { Metadata } from "next";
import { DM_Sans } from "next/font/google";
import "./globals.css";
import NavigationBar from "@/components/NavigationBar";
import Footer from "@/components/Footer";

const fontDMSans = DM_Sans({ subsets: ["latin"], variable: "--font-dm-sans" });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${fontDMSans.variable} min-h-screen min-w-80 font-main`}>
        <NavigationBar />
        <main>
          <div className="mx-auto max-w-[90rem]">{children}</div>
        </main>
        <Footer />
      </body>
    </html>
  );
}
